services:
  - type: web
    name: bullet-news
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn BulletNEWS.wsgi:application
    plan: free
    envVars:
      - key: DEBUG
        value: 'False'
      - fromDotEnv: true

  - type: cron
    name: bullet-news-scraper
    schedule: '0 */3 * * *'
    command: python manage.py run_all_scrapper
    envVars:
      - fromDotEnv: true
