# Generated by Django 5.2 on 2025-05-13 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('PDF', 'PDF'), ('AUDIO', 'Audio')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_downloaded', models.BooleanField(default=False)),
            ],
        ),
    ]
